#!/bin/bash

./chessengine -infile workunits/workunits_lvl_5_mul_1.txt  -outfile results/level_6_mul_1.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_2.txt  -outfile results/level_6_mul_2.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_3.txt  -outfile results/level_6_mul_3.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_4.txt  -outfile results/level_6_mul_4.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_5.txt  -outfile results/level_6_mul_5.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_6.txt  -outfile results/level_6_mul_6.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_7.txt  -outfile results/level_6_mul_7.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_8.txt  -outfile results/level_6_mul_8.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_9.txt  -outfile results/level_6_mul_9.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_10.txt  -outfile results/level_6_mul_10.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_11.txt  -outfile results/level_6_mul_11.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_12.txt  -outfile results/level_6_mul_12.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_13.txt  -outfile results/level_6_mul_13.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_14.txt  -outfile results/level_6_mul_14.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_15.txt  -outfile results/level_6_mul_15.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_16.txt  -outfile results/level_6_mul_16.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_17.txt  -outfile results/level_6_mul_17.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_18.txt  -outfile results/level_6_mul_18.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_19.txt  -outfile results/level_6_mul_19.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_20.txt  -outfile results/level_6_mul_20.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_21.txt  -outfile results/level_6_mul_21.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_22.txt  -outfile results/level_6_mul_22.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_23.txt  -outfile results/level_6_mul_23.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_24.txt  -outfile results/level_6_mul_24.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_26.txt  -outfile results/level_6_mul_26.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_28.txt  -outfile results/level_6_mul_28.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_30.txt  -outfile results/level_6_mul_30.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_31.txt  -outfile results/level_6_mul_31.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_32.txt  -outfile results/level_6_mul_32.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_33.txt  -outfile results/level_6_mul_33.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_34.txt  -outfile results/level_6_mul_34.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_35.txt  -outfile results/level_6_mul_35.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_36.txt  -outfile results/level_6_mul_36.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_37.txt  -outfile results/level_6_mul_37.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_38.txt  -outfile results/level_6_mul_38.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_40.txt  -outfile results/level_6_mul_40.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_41.txt  -outfile results/level_6_mul_41.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_42.txt  -outfile results/level_6_mul_42.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_43.txt  -outfile results/level_6_mul_43.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_44.txt  -outfile results/level_6_mul_44.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_52.txt  -outfile results/level_6_mul_52.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_56.txt  -outfile results/level_6_mul_56.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_63.txt  -outfile results/level_6_mul_63.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_71.txt  -outfile results/level_6_mul_71.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_75.txt  -outfile results/level_6_mul_75.txt -maxlevel 6 -logtype cfen
./chessengine -infile workunits/workunits_lvl_5_mul_87.txt  -outfile results/level_6_mul_87.txt -maxlevel 6 -logtype cfen
